#!/bin/bash

for application in "Growl" "GrowlHelperApp"; do
  version=`osascript -e "get version of application \"$application\"" 2>/dev/null`
  if [ $? -eq 0 ]; then break; fi
done

case "$version" in
  "")
    echo "Growl not found: please install Growl and try again"
    exit 1
    ;;
  1.[012]*)
    $0-1.1.5 "$@"
    ;;
  *)
    $0-1.3 "$@"
    ;;
esac
